apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-frontend
  namespace: llm
  labels:
    app: llm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-frontend
  template:
    metadata:
      labels:
        app: llm-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: llm-frontend
        image: ghcr.io/datawikipro/igaming-llm-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://llm-admin"
        - name: HOSTNAME
          value: "0.0.0.0"
      nodeSelector:
        node-type: master
---
apiVersion: v1
kind: Service
metadata:
  name: llm-frontend
  namespace: llm
spec:
  selector:
    app: llm-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
